backend:
  name: git-gateway
  branch: main

media_folder: Static/Assets/images

collections:
  - name: "Contents"
    label: "Contents"
    extension: "json"
    files:
      - file: "Romulus/Static/Assets/data/contents.json"
        label: "Content"
        name: "Content"
        fields:
          - { name: Title, label: Title, widget: string }
          - { name: Footer, label: Footer, widget: string }

  - name: "page" 
    label: "Pages" 
    folder: "Romulus/Static" 
    create: true 
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
  
  - name: "Pages"
    label: "Page"
    description: "Add a page to your website"
    create: true 
    slug: "{{slug}}"
    files:
      - label: "Site Panels"
        create: true 
        slug: "{{slug}}"
        name: "Panel"
        file: "Romulus/Static/Assets/data/{{slug}}.json"
        fields:
          - label: "Panel List"
            name: "PanelList"
            widget: "list"
            fields:
              - { name: title, label: Panel Title, widget: "string", required: false}
              - { name: PanelText, label: Panel Text, widget: "markdown", required: false}
              - { name: PanelType, label: Panel Type, widget: "select", options: ["ImageLeft", "ImageRight", "FullWidth"]}
              - { name: PanelImage, label: Panel Image, widget: "image", required: false}
    fields: 
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
    - {label: "Title", name: "title", widget: "string"}


  - name: "Panels"
    label: "Homepage"
    description: "Add a panel to your homepage"
    files:
      - label: "Site Panels"
        name: "Panel"
        file: "Romulus/Static/Assets/data/contents-1.json"
        fields:
          - label: "Panel List"
            name: "PanelList"
            widget: "list"
            fields:
              - { name: PanelTitle, label: Panel Title, widget: "string", required: false}
              - { name: PanelText, label: Panel Text, widget: "markdown", required: false}
              - { name: PanelType, label: Panel Type, widget: "select", options: ["ImageLeft", "ImageRight", "FullWidth"]}
              - { name: PanelImage, label: Panel Image, widget: "image", required: false}

  
  





  
